### ISSUE TITLE
p.197 리듀싱 연산

### ISSUE THREAD

**Issue by gbeea1004** [CODE-SLiPPER/ReadingRecord#3]
> collect 도 다양한 요소 누적 방식을 인수로 받아 스트림을 최종 결과로 도출하는 리듀싱 연산을 수행할 수 있다.

라고 하는데 **리듀싱 연산**이 무엇인가요?

**Comment by zingoworks** [comment]
무엇인가요?

**Comment by SeEunKim** [comment]
리듀싱 연산은 Java 8 Stream, Collectors에서 제공하는 API 입니다. 
입력 스트림 요소에 대한 감소를 수행하는 Collector를 반환합니다. 

<T> Collector<T,?,Optional<T>> reducing(BinaryOperator<T> op)
<T> Collector<T,?,T> reducing(T identity,
                              BinaryOperator<T> op)
<T,U> Collector<T,?,U> reducing(U identity,
                                Function<? super T,? extends U> mapper,
                                BinaryOperator<U> op)

각각에 예제를 보면 이해가 쉬울 것 같아 예제를 풀이와 함께 작성해보았습니다. 

<pre><code class='language-java' lang='java'>&lt;T&gt; Collector&lt;T,?,Optional&lt;T&gt;&gt; reducing(BinaryOperator&lt;T&gt; op)
  
// example
  
Stream&lt;Integer&gt; s = Stream.of(5, 10, 20, 50);
Integer i = s.collect(Collectors.reducing((integer, integer2) -&gt; integer2 - integer)).orElse(-1);
System.out.println(i);
// 35
</code></pre>
<ul>
<li>BinaryOperator : 인수 2개를 받아, 인수와 같은 타입의 값을 리턴하는 함수를 의미.</li>
<li>op : 입력 스트림의 값을 하나씩 줄여가면서 연산하는 op</li>

</ul>
<ul>
<li>예제에서는 op : (integer, integer2) -&gt; integer2 - integer  // 숫자 1, 2를 입력받아 2-1 값을 연산합니다. </li>
<li>입력 스트림값은 5, 10, 20, 50</li>

</ul>
<figure><table>
<thead>
<tr><th>처리과정</th><th>5</th><th>10</th><th>20</th><th style='text-align:center;' >50</th></tr></thead>
<tbody><tr><td>1) 5, 10이 인수로 들어옵니다.<br>integer = 5<br>integer2 = 10<br>10-5 = 5 </td><td>O</td><td>O</td><td>&nbsp;</td><td style='text-align:center;' >&nbsp;</td></tr><tr><td>2)  1의 결과인 5, 스트림에 3번째 요소인 20이 들어옵니다.<br>integer = 5<br>integer2 = 20<br>20-5 = 15</td><td>&nbsp;</td><td>&nbsp;</td><td>O</td><td style='text-align:center;' >&nbsp;</td></tr><tr><td>3) 2의 결과인 15, 스트림에 4번째 요소인 50이 들어옵니다.<br>integer = 15<br>integer2 = 50<br>50 - 15 = 35</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td style='text-align:center;' >O</td></tr></tbody>
</table></figure>
<hr />
<pre><code class='language-java' lang='java'>&lt;T&gt; Collector&lt;T,?,T&gt; reducing(T identity,
                              BinaryOperator&lt;T&gt; op)
  
Stream&lt;Integer&gt; s = Stream.of(5, 10, 20, 50);
        Integer i = s.collect(Collectors.reducing(1, (integer, integer2)
                -&gt; integer2 - integer));
System.out.println(i);  
// 36
</code></pre>
<ul>
<li>Identity : 초기값</li>

</ul>
<figure><table>
<thead>
<tr><th>처리과정</th><th>5</th><th>10</th><th>20</th><th>50</th></tr></thead>
<tbody><tr><td>1) 초기값 1과, 스트림에 1번째 요소인 5가 들어옵니다.<br>Integer = 1<br>integer2 = 5<br>5 - 1 = 4</td><td>O</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>2) 1의 결과인 4와 스트림의 2번째 요소인 10이 들어옵니다.<br>Integer = 4<br>integer2 = 10<br>10 - 4 = 6</td><td>&nbsp;</td><td>O</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>3) 2의 결과인 6과 스트림의 3번째 요소인 20이 들어옵니다.<br>Integer = 6<br>integer2 = 20<br>20 - 6 = 14</td><td>&nbsp;</td><td>&nbsp;</td><td>O</td><td>&nbsp;</td></tr><tr><td>4) 3의 결과인 14와 스트림의 4번째 요소인 50이 들어옵니다.<br>Integer = 14<br>integer2 = 50<br>50 - 14 = 36</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>O</td></tr></tbody>
</table></figure>
<hr />
<pre><code class='language-java' lang='java'>&lt;T,U&gt; Collector&lt;T,?,U&gt; reducing(U identity,
                                Function&lt;? super T,? extends U&gt; mapper,
                                BinaryOperator&lt;U&gt; op)
  
Stream&lt;Integer&gt; s = Stream.of(5, 10, 20, 50).parallel();
String str = s.collect(Collectors.reducing(
  &quot;&quot;,
  x -&gt; Integer.toString(x),
  (s1, s2) -&gt; s1 + s2));
System.out.println(str);
// 5102050
</code></pre>
<ul>
<li>mapper : 각 입력값에 적용할 mapper 함수</li>

</ul>
<figure><table>
<thead>
<tr><th>처리과정</th><th>5</th><th>10</th><th>20</th><th>50</th></tr></thead>
<tbody><tr><td>1) 초기값은 &quot;&quot;<br>스트림에서 첫번째 인수 5를 문자로 변환한 다음에 (5 -&gt; String)<br>s1 = &quot;&quot;<br>s2 = &quot;5&quot;<br>&quot;&quot; + &quot;5&quot; = &quot;5&quot;</td><td>O</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>2) 1의 결과인 &quot;5&quot;와 스트림 2번째 요소인 10이 들어옵니다.<br>10을 문자로 변환한 다음에 (10 -&gt; &quot;10&quot;)<br>s1 = &quot;5&quot;<br>s2 = &quot;10&quot;<br>&quot;5&quot; + &quot;10&quot; = &quot;510&quot;</td><td>&nbsp;</td><td>O</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>3) 2의 결과인 &quot;510&quot;과 스트림의 3번째 요소인 20이 들어옵니다.<br>20을 문자로 변환한 다음에 (20 -&gt; &quot;20&quot;)<br>s1 = &quot;510&quot;<br>s2 = &quot;20&quot;<br>&quot;510&quot; + &quot;20&quot; = &quot;51020&quot;</td><td>&nbsp;</td><td>&nbsp;</td><td>O</td><td>&nbsp;</td></tr><tr><td>4) 3의 결과인 &quot;51020&quot;과 스트림의 4번째 요소인 50이 들어옵니다. <br>50을 문자열로 변환한 다음에 (50 -&gt; &quot;50&quot;)<br>s1 = &quot;51020&quot;<br>s2 = &quot;50&quot;<br>&quot;51020&quot; + &quot;50&quot; = &quot;5102050&quot;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>O</td></tr></tbody>
</table></figure>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<blockquote><p><a href='https://www.logicbig.com/how-to/code-snippets/jcode-java-8-streams-collectors-reducing.html' target='_blank' class='url'>https://www.logicbig.com/how-to/code-snippets/jcode-java-8-streams-collectors-reducing.html</a></p>
<p><a href='https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#reducing-U-java.util.function.Function-java.util.function.BinaryOperator-' target='_blank' class='url'>https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#reducing-U-java.util.function.Function-java.util.function.BinaryOperator-</a></p>
</blockquote>
</body>
</html>
