### ISSUE TITLE
p.208 제네릭과 와일드카드

### ISSUE THREAD

**Issue by gbeea1004** [CODE-SLiPPER/ReadingRecord#4]
제네릭과 와일드카드가 뭔지 햇갈려요..
이게 무엇인지.. 어떤 상황에 쓰는걸까요?

**Comment by kimse9450** [comment]
제네릭 

- 파라미터 : 값(인자, argument)을 받아 파라미터 변수와 바인딩하고 메서드 내부에서 사용함
- 타입 파라미터
  - 파라미터인데, 그 값이 타입인 것
  - 객체를 생성할 때 타입을 받아서 그 타입으로 만듬
  - 인자를 넘겨받을 때에는 <타입> 으로

- 지금은 이 타입을 모르지만, 이 타입이 정해지면 그 타입 특성에 맞게 사용하겠다!



와일드 카드 

- 타입 파라미터가 의미있게 사용되는가? 놉 사용되지않는다면 와일드카드 사용
  -  무엇이라도 들어가도된다 : 모른다, 몰라도된다, 무엇이 들어올지 알 필요없다
  - 데이터(타입)보다 데이터가 있으니깐 무엇을 한다에 관심

- 지금도 이 타입을 모르고, 앞으로도 모를 것이다!



[제네릭 vs 와일드카드]
- 타입 파라미터가 의미있게 사용되는가?

(1) 그렇다면 제네릭
(2) 아니라면 와일드카드

    static void printList1(List<?> list) {
      list.add(list.get(1)); // 컴파일 실패 
    // 1. 와일드 카드는 list에 담긴 원소에는 전혀 관심이 없기 때문에 원소와 관련된 add 메소드를 사용할 수 없다. 
    // 2. 단, null은 들어갈 수 있다. 
    } 
      
    static <T> void printList2(List<T> list) { 
    // 1. 제네릭은 list에 담긴 원소에 관심을 갖기 때문에 원소와 관련된 add 메소드를 사용할 수 있다. 
    // 2. 당연히 null도 들어갈 수 있다. list.add(list.get(1)); // 컴파일 성공 
    }
    
    



 출처 

https://vvshinevv.tistory.com/55

https://jinbroing.tistory.com/228

**Comment by gbeea1004** [comment]
http 의 와일드 카드와 혼동주의!
