### ISSUE TITLE
p.245 HotSpot

### ISSUE THREAD

**Issue by gbeea1004** [CODE-SLiPPER/ReadingRecord#6]
JVM 의 핫스팟의 정의가 애매해서 질문드려요

**Comment by LYJr** [comment]
핫스팟이란 오라클에서 제작한 것으로 오라클 핫스팟이라고도 불리며 
정리하자면 jvm의 일종입니다.
오라클 핫스팟 JVM 외에도 IBM JVM을 비롯한 다양한 JVM이 존재합니다.
