### ISSUE TITLE
p.278 가변 인수

### ISSUE THREAD

**Issue by SeEunKim** [CODE-SLiPPER/ReadingRecord#8]
오버로딩 VS 가변 인수
"내부적으로 가변 인수 버전은 추가 배열을 할당해서 리스트로 감싼다. 따라서 배열을 할당하고 초기화하며 나중에 가비지 컬렉션을 하는 비용을 지불해야 한다. "
이 부분이 잘 이해가 되지 않아서요...

**Comment by gbeea1004** [comment]
**가변인자의 정의**를 일단 설명드릴게요.

기존에는 메서드의 매개변수의 갯수가 고정이었는데, 

**JDK 1.5** 부터는 동적으로 매개변수를 지정해 줄 수 있도록 가변인자라는 것이 생겼습니다.

```java
static <E> List<E> of(E... elements)
```

가변인자는 위와 같이 '**타입... 변수명**'과 같은 형식으로 선언합니다.

가변인자는 내부적으로 배열을 생성해서 사용합니다.

여기서 주의할점은 **가변인자가 선언된 메서드를 호출할 때마다 배열이 새로 생성되는 점**입니다.



질문 주신 내용을 다시 살펴봅시다.

> 내부적으로 가변 인수 버전은 추가 배열을 할당해서 리스트로 감싼다. 
> 따라서 배열을 할당하고 초기화하며 나중에 가비지 컬렉션을 하는 비용을 지불해야 한다. 

1. 메서드를 호출하면 새로운 배열이 생성 (배열 할당)
2. 거기에 인자값을 넣어준다. (초기화)
3. 배열은 List에 값을 넣어준 뒤 사용을 안하므로, 시간이 지나면 가비지 컬렉션에 의해 제거된다. (가비지 컬렉션을 하는 비용)



## 참고 ) 가변인자를 사용할 때 주의 사항

* 가변인자는 여려개 사용할 수 없다.
* 가변인자는 항상 파라미터 마지막에 위치해야 한다.
* 가변인자를 사용하면 인자값을 넣지않아도 정상적으로 실행이 되므로, 방어코드를 작성해야한다.



가변인자를 사용한 대표적인 예로 우리가 종종 사용하는 **printf()** 메서드가 있습니다.

```java
public PrintStream printf(String format, Object ... args) {
    return format(format, args);
}
```

ex ) System.out.printf("나는 %s이고 %d 살", "김세은", 34);
