### ISSUE TITLE
P.286 computeIfAbsent, computeIfPresent

### ISSUE THREAD

**Issue by SeEunKim** [CODE-SLiPPER/ReadingRecord#9]
computeIfAbsent : 제공된 키에 해당하는 값이 없으면 새롭게 계산하고 맵에 추가
computeIfPresent : 제공된 키가 존재하면 새 값을 계산하고 맵에 추가 
두 개가 너무 헷갈리네요 ......

**Comment by gbeea1004** [comment]
두 정의를 먼저 살펴볼게요.

### computeIfAbsent

* 제공된 키에 해당하는 값이 없거나 null 이면 맵에 추가한다.
* 제공된 키가 없으면 맵에 추가한다.

### computeIfPresent

* 제공된 키가 존재하면 새 값을 계산하고 맵에 추가한다.


토의하면서 같이 실습해보았지만, computeIfAbsent는 **제공된 키가 없어도** 맵에 추가합니다.

이 부분이 책에는 빠져있어서 애매했어요

**Comment by gbeea1004** [comment]
@SeEunKim
